Repository HuobiGroup/huobi-chain, pull requests merged in 2020-09, with the labels that each got.

#123 feat: add 2 query interface of governance
  services/governance/src/lib.rs
Labels: approved, lgtm, size/S

#125 refactor(service): update riscv service
  Cargo.lock
  Cargo.toml
  Makefile
  services/admission_control/Cargo.toml
  services/admission_control/src/lib.rs
  services/admission_control/src/tests.rs
  services/asset/Cargo.toml
  services/asset/src/lib.rs
  services/authorization/Cargo.toml
  services/authorization/src/lib.rs
  services/governance/Cargo.toml
  services/governance/src/lib.rs
  services/kyc/Cargo.toml
  services/kyc/src/lib.rs
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  services/riscv/src/error.rs
  services/riscv/src/lib.rs
  services/riscv/src/tests/assert
  services/riscv/src/tests/assert.c
  services/riscv/src/tests/simple_storage
  services/riscv/src/tests/simple_storage.c
  services/riscv/src/tests/test_code.js
  services/riscv/src/tests/write_read
  services/riscv/src/tests/write_read.c
  services/riscv/src/vm/chain_interface.rs
  src/main.rs
  tests/e2e/config/genesis.toml
  tests/e2e/riscv_contracts/contract_test
  tests/e2e/riscv_contracts/contract_test.c
  tests/e2e/src/riscv.test.ts
Labels: approved, lgtm, size/XXL

#126 feat: bump muta to v0.2.0-rc.2.1
  Cargo.lock
  Cargo.toml
  Makefile
  config/chain.toml
  config/genesis.toml
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/authorization/Cargo.toml
  services/governance/Cargo.toml
  services/kyc/Cargo.toml
  services/kyc/src/expression/evaluation.rs
  services/kyc/src/expression/mod.rs
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  tests/e2e/config/chain.toml
  tests/e2e/config/genesis.toml
  tests/e2e/package.json
  tests/e2e/src/governance2.test.ts.bk
  tests/e2e/src/kyc.test.ts
  tests/e2e/src/riscv.test.ts
Labels: approved, lgtm, size/L

#127 build: build v0.5.0-rc.2
  CHANGELOG/CHANGELOG-0.5.md
  Cargo.lock
  Cargo.toml
  services/asset/Cargo.toml
  services/governance/Cargo.toml
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  src/main.rs
Labels: size/L

#129 fix: asset service verify bugs, riscv sub overflow bug
  services/asset/src/lib.rs
  services/asset/src/types.rs
  services/riscv/src/vm/chain_interface.rs
Labels: approved, lgtm, size/L

#131 build: build v0.5.0
  CHANGELOG/CHANGELOG-0.5.md
  Cargo.lock
  Cargo.toml
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/authorization/Cargo.toml
  services/governance/Cargo.toml
  services/kyc/Cargo.toml
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  services/timestamp/Cargo.toml
  services/transfer_quota/Cargo.toml
  src/bin/huobi-chain-payment.rs
  src/main.rs
Labels: approved, lgtm, size/XL

#133 fix(asset): allow to mint an asset with 0 payload and now return error when feed stale time
  services/asset/src/types.rs
  services/timestamp/src/lib.rs
Labels: approved, lgtm, size/S

#132 fix(kyc): fix validate TagName, TagValue and OrgName format while ser/de
  services/kyc/src/expression/evaluation.rs
  services/kyc/src/expression/mod.rs
  services/kyc/src/expression/node.rs
  services/kyc/src/expression/token.rs
  services/kyc/src/lib.rs
  services/kyc/src/tests.rs
  services/kyc/src/types.rs
  services/transfer_quota/src/tests/mod.rs
Labels: approved, lgtm, size/XL

#134 fix(riscv): add set_admin for riscv and fix contract_call missing bech32 address
  Cargo.lock
  services/riscv/Cargo.toml
  services/riscv/src/authorization.rs
  services/riscv/src/lib.rs
  services/riscv/src/tests/assert.c
  services/riscv/src/tests/general.c
  services/riscv/src/tests/mod.rs
  services/riscv/src/tests/simple_storage.c
  services/riscv/src/tests/test_code.js
  services/riscv/src/tests/write_read.c
  services/riscv/src/types.rs
  services/riscv/src/vm/c/libpvm.a
  services/riscv/src/vm/c/pvm.c
  services/riscv/src/vm/c/pvm.h
  services/riscv/src/vm/syscall/chain_interface.rs
  src/bin/huobi-chain-payment.rs
  src/main.rs
  tests/e2e/src/common/utils.ts
  tests/integration/mod.rs
Labels: approved, lgtm, size/XXL

#135 build: bump version to v0.6.0
  Cargo.lock
  Cargo.toml
  rust-toolchain
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/authorization/Cargo.toml
  services/authorization/src/lib.rs
  services/governance/Cargo.toml
  services/governance/src/lib.rs
  services/kyc/Cargo.toml
  services/kyc/src/expression/token.rs
  services/metadata/Cargo.toml
  services/metadata/src/tests/mod.rs
  services/riscv/Cargo.toml
  services/timestamp/Cargo.toml
  services/transfer_quota/Cargo.toml
  src/bin/huobi-chain-payment.rs
  src/main.rs
  tests/integration/mod.rs
Labels: approved, lgtm, size/L
