Repository HuobiGroup/huobi-chain, pull requests merged in 2020-08, with the labels that each got.

#106 build: No release prepare
  jenkins-x.yml
Labels: size/XS

#107 chore: add bech32_address_hrp to genesis.toml
  config/genesis.toml
  devtools/docker-compose/node-genesis.toml
  services/governance/src/tests/test_genesis.toml
  tests/e2e/change_validators/templates/genesis.toml.template
  tests/e2e/genesis.toml
  tests/integration/test_genesis.toml
Labels: approved, lgtm, size/XS

#108 fix: fix kyc orgName and tagName length to 32, values up to 16
  services/kyc/src/tests.rs
  services/kyc/src/types.rs
Labels: approved, lgtm, size/M

#109 build: Release v0.5.0-beta.2
  CHANGELOG/CHANGELOG-0.5.md
  Cargo.lock
  Cargo.toml
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/authorization/Cargo.toml
  services/governance/Cargo.toml
  services/kyc/Cargo.toml
  services/metadata/Cargo.toml
  services/metadata/src/tests/mod.rs
  services/riscv/Cargo.toml
Labels: approved, lgtm, size/L

#110 fix: remove cycle of hook_transfer_from
  services/asset/src/lib.rs
Labels: approved, lgtm, size/XS

#111 feat: use random_leader by default
  Cargo.toml
Labels: approved, lgtm, size/XS

#112 fix: remove deprecated "tx_fee_inlet_address" in genesis
  config/genesis.toml
  services/governance/src/tests/test_genesis.toml
  tests/e2e/genesis.toml
  tests/integration/test_genesis.toml
Labels: approved, lgtm, size/XS

#115 fix: give clear reason for admission control fails
  services/admission_control/src/lib.rs
  services/authorization/src/lib.rs
Labels: approved, lgtm, size/S

#117 Revert "fix: give clear reason for admission control fails"
  services/admission_control/src/lib.rs
  services/authorization/src/lib.rs
Labels: approved, lgtm, size/S

#118 fix!: give clear reason for admission control fails
  services/admission_control/src/lib.rs
  services/authorization/src/lib.rs
Labels: approved, lgtm, size/S

#113 fix(govern): service context on updating metadata
  services/governance/src/lib.rs
  tests/integration/service_test.rs
Labels: approved, lgtm, size/S

#114 test: fix e2e test
  Cargo.lock
  Cargo.toml
  Makefile
  package.json
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/authorization/Cargo.toml
  services/governance/Cargo.toml
  services/kyc/Cargo.toml
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  tests/e2e/.gitignore
  tests/e2e/config/chain.toml
  tests/e2e/config/genesis.toml
  tests/e2e/genesis.toml
  tests/e2e/jest.config.js
  tests/e2e/package.json
  tests/e2e/src/asset.test.ts
  tests/e2e/src/basic.test.ts
  tests/e2e/src/common/helper.ts
  tests/e2e/src/common/utils.ts
  tests/e2e/src/governance.test.ts
  tests/e2e/src/governance2.test.ts.bk
  tests/e2e/src/kyc.test.ts
  tests/e2e/src/riscv.test.ts.bk
  tests/e2e/tsconfig.json
  tests/e2e/utils.ts
  tests/e2e/wait-for-it.sh
  tests/e2e/yarn.lock
  yarn.lock
Labels: approved, lgtm, size/XXL

#119 fix: adapt muta v0.2.0-beta.4
  Cargo.lock
  Cargo.toml
  config/chain.toml
  devtools/docker-compose/node-1-chain.toml
  devtools/docker-compose/node-2-chain.toml
  devtools/docker-compose/node-3-chain.toml
  devtools/docker-compose/node-4-chain.toml
  services/admission_control/Cargo.toml
  services/admission_control/src/lib.rs
  services/asset/Cargo.toml
  services/asset/src/lib.rs
  services/authorization/Cargo.toml
  services/authorization/src/lib.rs
  services/governance/Cargo.toml
  services/governance/src/lib.rs
  services/kyc/Cargo.toml
  services/kyc/src/lib.rs
  services/metadata/Cargo.toml
  services/metadata/src/lib.rs
  services/riscv/Cargo.toml
  services/riscv/src/lib.rs
  services/riscv/src/vm/syscall/environment.rs
  src/main.rs
  tests/e2e/change_validators/templates/chain.toml.template
  tests/e2e/config/chain.toml
  tests/e2e/package.json
  tests/e2e/src/governance.test.ts
  tests/e2e/yarn.lock
Labels: approved, lgtm, size/XL

#120 build: build v0.5.0-beta.4
  CHANGELOG/CHANGELOG-0.5.md
  Cargo.lock
  Cargo.toml
  services/asset/Cargo.toml
  services/governance/Cargo.toml
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  src/main.rs
Labels: approved, lgtm, size/L

#121 feat: change the kyc supported tags
  services/kyc/src/error.rs
  services/kyc/src/lib.rs
  services/kyc/src/tests.rs
  tests/e2e/config/genesis.toml
  tests/e2e/src/kyc.test.ts
Labels: approved, lgtm, size/L

#122 build: build v0.5.0-rc
  Cargo.lock
  Cargo.toml
  services/admission_control/Cargo.toml
  services/asset/Cargo.toml
  services/authorization/Cargo.toml
  services/governance/Cargo.toml
  services/kyc/Cargo.toml
  services/metadata/Cargo.toml
  services/riscv/Cargo.toml
  src/main.rs
Labels: approved, lgtm, size/L
